### ISSUE TITLE
Subscriptions are added to the user before they are payed

### ISSUE THREAD

**Issue by bonflintstone** [nghildebrandt/coffee#46]
This is basically fucked. I guess we gotta have a new system where we keep the cart filled until the charge is done. Maybe we actually only create the order after the charge.

**Comment by bonflintstone** [comment]
Soooo.... how about:

cart#show (view) -> orders/addresses#new (view) -> order/addresses#create (redirect) -> order/charges#new (view) -> order/charges#create (creates the order, goes to order#show)

Problems with this design are:
 - when we create the address, where do we store it? the order does not exist yet. Maybe we add a address to the cart?

**Comment by nghildebrandt** [comment]
I thought about setting the address after you paid, but that is also no good. Therefore, I also think that is the best solution, maybe you could also like a presubscription and paid subscription, the way that we have cart and orders

**Comment by bonflintstone** [comment]
Orrr...
We just say whatever the user puts into shipping address is gonna be the new address of the user. In that way we only update the users address and can save it there. In that way we dont lose it etc.

**Comment by bonflintstone** [comment]
Wait but this also does not quite work naming wise. If we have addresses nested in orders we need the order id

**Comment by bonflintstone** [comment]
Ok fuck it. Ill just make it the same view and make it work somehow nicely with javscript
